# Generated by Django 4.2.1 on 2023-05-06 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clancoin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='treathistory',
            name='child_user',
        ),
        migrations.RemoveField(
            model_name='treathistory',
            name='parent_user',
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('balance', models.IntegerField()),
                ('is_parent', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='treathistory',
            name='from_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='clancoin.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treathistory',
            name='to_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='clancoin.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='child_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_user', to='clancoin.user'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='parent_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_user', to='clancoin.user'),
        ),
        migrations.DeleteModel(
            name='ChildUser',
        ),
        migrations.DeleteModel(
            name='ParentUser',
        ),
    ]
