# Generated by Django 4.2.1 on 2023-06-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clancoin', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=64),
        ),
    ]
